"""inital migrattions

Revision ID: 214fb4b9d80a
Revises: 
Create Date: 2020-12-29 20:30:57.115079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214fb4b9d80a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_by_category', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('posts_by_category', sa.Column('post_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'posts_by_category', type_='foreignkey')
    op.create_foreign_key(None, 'posts_by_category', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'posts_by_category', 'post', ['post_id'], ['id'])
    op.drop_column('posts_by_category', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts_by_category', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'posts_by_category', type_='foreignkey')
    op.drop_constraint(None, 'posts_by_category', type_='foreignkey')
    op.create_foreign_key(None, 'posts_by_category', 'post', ['id'], ['id'])
    op.drop_column('posts_by_category', 'post_id')
    op.drop_column('posts_by_category', 'category_id')
    # ### end Alembic commands ###
